### ISSUE TITLE
Up/down is printed to terminal instead of interpreted as key press events

### ISSUE THREAD

**Issue by julianbuettner** [Preyde/cli_select#1]
Using the arrow keys print characters instead of changing the selection.  
The [raw mode](crossterm::terminal::enable_raw_mode)
has to be entered to make this works.

This also required changing the rendering logic.

System: Ubuntu, WSL, Terminal App by Microsoft on Windows.  
However I think the issue is system independant.

In case this will not be fixed and others come across this crate / repository:  
A good alternative is [dialoguer](https://docs.rs/dialoguer)

**Comment by Preyde** [comment]
Hello julianbuettner,

thank you for using cli_select and opening this issue.

It is resolved by commit 760604c.
As you suggested the newest version of cli_select (0.1.5) now uses raw mode while listening for keystrokes.

Further improvements will follow soon.
Kind regards

**Comment by julianbuettner** [comment]
Thank you!
